Hacky fix for WinMergeReporter exception on win7 64 bits
java.lang.Error: java.io.IOException: Cannot run program "C:\Program": CreateProcess error=2, Le fichier spécifié est introuvable
	at com.spun.util.ObjectUtils.throwAsError(ObjectUtils.java:140)
	at org.approvaltests.Approvals.verify(Approvals.java:253)
	at org.approvaltests.Approvals.verify(Approvals.java:194)
	at org.approvaltests.Approvals.verify(Approvals.java:205)
	at org.approvaltests.Approvals.verify(Approvals.java:56)
	at encode.audio.entrypoint.AudioAnnounceEngineTest.checkApprovalTestsReporter(AudioAnnounceEngineTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.io.IOException: Cannot run program "C:\Program": CreateProcess error=2, Le fichier spécifié est introuvable
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
	at java.lang.Runtime.exec(Runtime.java:617)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at org.approvaltests.reporters.GenericDiffReporter.report(GenericDiffReporter.java:40)
	at org.approvaltests.approvers.FileApprover.reportFailure(FileApprover.java:46)
	at org.approvaltests.Approvals.verify(Approvals.java:238)
	... 30 more
Caused by: java.io.IOException: CreateProcess error=2, Le fichier spécifié est introuvable
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:376)
	at java.lang.ProcessImpl.start(ProcessImpl.java:136)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
	... 36 more

C:\Program Files\WinMerge\WinMergeU.exe "C:\code\cara-dojos\EncodeAudioLegacy\.\src\test\java\encode\audio\entrypoint\AudioAnnounceEngineTest.checkApprovalTestsReporter.received.txt" "C:\code\cara-dojos\EncodeAudioLegacy\.\src\test\java\encode\audio\entrypoint\AudioAnnounceEngineTest.checkApprovalTestsReporter.approved.txt"